FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
COPY internal/ ./internal/
COPY cmd/ ./cmd/
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /driftguard ./cmd/driftguard

FROM alpine:3.19
RUN apk add --no-cache curl ca-certificates
WORKDIR /app
COPY --from=builder /driftguard /app/driftguard
EXPOSE 8000
ENTRYPOINT ["/app/driftguard"]
